### ISSUE TITLE
Small request: Add Golem topic to repository

### ISSUE THREAD

**Issue by cryptobench** [broadcastmonkey/ChessOnGolem#1]
Hello!

It would be much appreciated if you could add the topic **golem** to the repository!
That would mean people could find all the awesome projects by just exploring the topic **golem** here https://github.com/topics/golem, and hopefully create a little bit more exposure for this awesome project! :heart:

There will be a settings wheel on the right side of the screenshot if you head over to your repository's main page, click that and you should see the option to add a topic.
![image](https://user-images.githubusercontent.com/33448819/104737054-0fd5e200-5744-11eb-9249-517e1ceffc8d.png)

**Comment by warburg-pb** [comment]
thanks for the suggestion, just added golem to topics :)
